In [12]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [14]:
import os

print(os.getcwd())

D:\2025aa05525-wilp.bits-pilani.ac.in\2\UDP\NLP_Group52\notebooks

In [16]:
import pandas as pd

df = pd.read_csv(r"../data/NewsCategorizer.csv")

print(df.shape)
df.head()

(50000, 5)

,category,headline,links,short_description,keywords
0,WELLNESS,143 Miles in 35 Days: Lessons Learned,https://www.huffingtonpost.com/entry/running-l...,Resting is part of training. I've confirmed wh...,running-lessons
1,WELLNESS,Talking to Yourself: Crazy or Crazy Helpful?,https://www.huffingtonpost.com/entry/talking-t...,Think of talking to yourself as a tool to coac...,talking-to-yourself-crazy
2,WELLNESS,Crenezumab: Trial Will Gauge Whether Alzheimer...,https://www.huffingtonpost.com/entry/crenezuma...,The clock is ticking for the United States to ...,crenezumab-alzheimers-disease-drug
3,WELLNESS,"Oh, What a Difference She Made",https://www.huffingtonpost.com/entry/meaningfu...,"If you want to be busy, keep trying to be perf...",meaningful-life
4,WELLNESS,Green Superfoods,https://www.huffingtonpost.com/entry/green-sup...,"First, the bad news: Soda bread, corned beef a...",green-superfoods

In [17]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nFirst 5 Rows:")
print(df.head())

Shape: (50000, 5)

Columns:
Index(['category', 'headline', 'links', 'short_description', 'keywords'], dtype='object')

First 5 Rows:
   category                                           headline  \
0  WELLNESS              143 Miles in 35 Days: Lessons Learned
1  WELLNESS       Talking to Yourself: Crazy or Crazy Helpful?
2  WELLNESS  Crenezumab: Trial Will Gauge Whether Alzheimer...
3  WELLNESS                     Oh, What a Difference She Made
4  WELLNESS                                   Green Superfoods

                                               links  \
0  https://www.huffingtonpost.com/entry/running-l...
1  https://www.huffingtonpost.com/entry/talking-t...
2  https://www.huffingtonpost.com/entry/crenezuma...
3  https://www.huffingtonpost.com/entry/meaningfu...
4  https://www.huffingtonpost.com/entry/green-sup...

                                   short_description  \
0  Resting is part of training. I've confirmed wh...
1  Think of talking to yourself as a tool to coac...
2  The clock is ticking for the United States to ...
3  If you want to be busy, keep trying to be perf...
4  First, the bad news: Soda bread, corned beef a...

                             keywords
0                     running-lessons
1           talking-to-yourself-crazy
2  crenezumab-alzheimers-disease-drug
3                     meaningful-life
4                    green-superfoods

In [18]:
df["text"] = (
    df["headline"].fillna("") + " " +
    df["short_description"].fillna("")
)

df[["category", "text"]].head()

   category                                               text
0  WELLNESS  143 Miles in 35 Days: Lessons Learned Resting ...
1  WELLNESS  Talking to Yourself: Crazy or Crazy Helpful? T...
2  WELLNESS  Crenezumab: Trial Will Gauge Whether Alzheimer...
3  WELLNESS  Oh, What a Difference She Made If you want to ...
4  WELLNESS  Green Superfoods First, the bad news: Soda bre...

In [19]:
import re

def preprocess(text):
    text = str(text).lower()

    text = re.sub(r'[^a-zA-Z ]', ' ', text)

    stop_words = {
        'the','a','an','is','are','was','were',
        'and','or','of','to','in','for','on',
        'with','at','by'
    }

    words = text.split()

    words = [word for word in words
             if word not in stop_words]

    return " ".join(words)

In [20]:
df["clean_text"] = df["text"].apply(preprocess)

df[["text","clean_text"]].head()

,text,clean_text
0,143 Miles in 35 Days: Lessons Learned Resting ...,miles days lessons learned resting part traini...
1,Talking to Yourself: Crazy or Crazy Helpful? T...,talking yourself crazy crazy helpful think tal...
2,Crenezumab: Trial Will Gauge Whether Alzheimer...,crenezumab trial will gauge whether alzheimer ...
3,"Oh, What a Difference She Made If you want to ...",oh what difference she made if you want be bus...
4,"Green Superfoods First, the bad news: Soda bre...",green superfoods first bad news soda bread cor...

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(df["clean_text"])

y = df["category"]

print(X.shape)

(50000, 5000)

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(40000, 5000)
(10000, 5000)

In [23]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [24]:
predictions = model.predict(X_test)

print(predictions[:10])

['FOOD & DRINK' 'POLITICS' 'WELLNESS' 'ENTERTAINMENT' 'WORLD NEWS'
 'POLITICS' 'POLITICS' 'SPORTS' 'WELLNESS' 'WORLD NEWS']

In [25]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    predictions
)

print("Accuracy:", accuracy)

Accuracy: 0.7994

In [ ]:
# Task 2 : Vector Embedding

In [28]:
from gensim.models import Word2Vec

In [29]:
sentences = [text.split() for text in df["clean_text"]]

word2vec_model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

In [30]:
word2vec_model.wv.most_similar("health")

[('mental', 0.8333250284194946),
 ('care', 0.7965632081031799),
 ('act', 0.7956607341766357),
 ('affordable', 0.7736256122589111),
 ('insurance', 0.7656875848770142),
 ('financial', 0.7575644254684448),
 ('income', 0.7530089616775513),
 ('physical', 0.7496865391731262),
 ('benefits', 0.7410072088241577),
 ('education', 0.7365702390670776)]

In [ ]:
# Task 3 : POS Tagging

In [33]:
import nltk

nltk.download('punkt_tab')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Santhoshn\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Santhoshn\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Santhoshn\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [35]:
import nltk

nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Santhoshn\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.

True

In [36]:
sample_text = df["text"].iloc[0]

tokens = nltk.word_tokenize(sample_text)

pos_tags = nltk.pos_tag(tokens)

print(pos_tags[:20])

[('143', 'CD'), ('Miles', 'NNS'), ('in', 'IN'), ('35', 'CD'), ('Days', 'NNS'), (':', ':'), ('Lessons', 'NNS'), ('Learned', 'VBD'), ('Resting', 'NNP'), ('is', 'VBZ'), ('part', 'NN'), ('of', 'IN'), ('training', 'NN'), ('.', '.'), ('I', 'PRP'), ("'ve", 'VBP'), ('confirmed', 'VBN'), ('what', 'WP'), ('I', 'PRP'), ('sort', 'VBP')]

In [37]:
important_words = []

for word, tag in pos_tags:
    if tag.startswith('NN') or tag.startswith('VB'):
        important_words.append(word)

print("Important Words:")
print(important_words)

Important Words:
['Miles', 'Days', 'Lessons', 'Learned', 'Resting', 'is', 'part', 'training', "'ve", 'confirmed', 'sort', 'knew', "'m", 'built', 'running', 'streaks', "'m", 'built', 'workouts', 'days', 'week', 'lots', 'cross', 'training', 'therapy', 'foam', 'rolling', "'ve", 'confirmed', "'m"]

In [ ]:
# Task 5 : Parsing

In [38]:
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp(sample_text)

for token in doc[:20]:
    print(
        token.text,
        token.dep_,
        token.head.text
    )

143 nummod Miles
Miles dep Learned
in prep Miles
35 nummod Days
Days pobj in
: punct Miles
Lessons nsubj Learned
Learned compound Resting
Resting nsubj is
is ROOT is
part attr is
of prep part
training pobj of
. punct is
I nsubj confirmed
've aux confirmed
confirmed ROOT confirmed
what dobj knew
I nsubj knew
sort advmod of

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=20)

X_tfidf = tfidf.fit_transform(df["clean_text"])

keywords = tfidf.get_feature_names_out()

print("Top Keywords:")
print(keywords)

Top Keywords:
['about' 'as' 'be' 'but' 'can' 'from' 'has' 'have' 'how' 'it' 'more' 'my'
 'new' 'not' 'that' 'this' 'we' 'what' 'you' 'your']

In [ ]:
# Task 4 : Hidden Markov Model (HMM)

In [40]:
from hmmlearn import hmm
import numpy as np

X_hmm = np.array([[0],[1],[0],[1],[1],[0]])

hmm_model = hmm.CategoricalHMM(
    n_components=2,
    random_state=42
)

hmm_model.fit(X_hmm)

print("HMM Model Created Successfully")

HMM Model Created Successfully

In [ ]:
# Task 1 : Neural Language Model

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model_lm = Sequential([
    Embedding(input_dim=5000,
              output_dim=100),
    LSTM(64),
    Dense(5000,
          activation='softmax')
])

model_lm.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=20)

X_tfidf = tfidf.fit_transform(df["clean_text"])

keywords = tfidf.get_feature_names_out()

print("Top Keywords:")
print(keywords)

Top Keywords:
['about' 'as' 'be' 'but' 'can' 'from' 'has' 'have' 'how' 'it' 'more' 'my'
 'new' 'not' 'that' 'this' 'we' 'what' 'you' 'your']

In [43]:
from hmmlearn import hmm
import numpy as np

X_hmm = np.array([[0],[1],[0],[1],[1],[0]])

hmm_model = hmm.CategoricalHMM(
    n_components=2,
    random_state=42
)

hmm_model.fit(X_hmm)

print("HMM Model Created Successfully")

HMM Model Created Successfully

In [44]:
from hmmlearn import hmm
import numpy as np

X_hmm = np.array([[0],[1],[0],[1],[1],[0]])

hmm_model = hmm.CategoricalHMM(
    n_components=2,
    random_state=42
)

hmm_model.fit(X_hmm)

print("HMM Model Created Successfully")

HMM Model Created Successfully

In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model_lm = Sequential([
    Embedding(input_dim=5000, output_dim=100),
    LSTM(64),
    Dense(5000, activation='softmax')
])

model_lm.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [46]:
print("===== NLP PROJECT RESULTS =====")

print("\nNews Classification Accuracy:")
print(accuracy)

print("\nTop Keywords:")
print(keywords)

print("\nSample POS Tags:")
print(pos_tags[:10])

print("\nWord2Vec Similar Words:")
print(word2vec_model.wv.most_similar("health")[:5])

print("\nHMM Status:")
print("Model Created Successfully")

print("\nParsing Status:")
print("Dependency Parsing Completed")

===== NLP PROJECT RESULTS =====

News Classification Accuracy:
0.7994

Top Keywords:
['about' 'as' 'be' 'but' 'can' 'from' 'has' 'have' 'how' 'it' 'more' 'my'
 'new' 'not' 'that' 'this' 'we' 'what' 'you' 'your']

Sample POS Tags:
[('143', 'CD'), ('Miles', 'NNS'), ('in', 'IN'), ('35', 'CD'), ('Days', 'NNS'), (':', ':'), ('Lessons', 'NNS'), ('Learned', 'VBD'), ('Resting', 'NNP'), ('is', 'VBZ')]

Word2Vec Similar Words:
[('mental', 0.8333250284194946), ('care', 0.7965632081031799), ('act', 0.7956607341766357), ('affordable', 0.7736256122589111), ('insurance', 0.7656875848770142)]

HMM Status:
Model Created Successfully

Parsing Status:
Dependency Parsing Completed

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model_lm = Sequential([
    Embedding(input_dim=5000, output_dim=100),
    LSTM(64),
    Dense(5000, activation='softmax')
])

model_lm.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [48]:
print("========== FINAL NLP RESULTS ==========")

print("\nClassification Accuracy:")
print(accuracy)

print("\nTop Keywords:")
print(keywords[:10])

print("\nSample POS Tags:")
print(pos_tags[:10])

print("\nWord2Vec Similar Words:")
print(word2vec_model.wv.most_similar("health")[:5])

print("\nParsing Status: Completed")
print("HMM Status: Completed")
print("Neural Language Model: Created Successfully")

========== FINAL NLP RESULTS ==========

Classification Accuracy:
0.7994

Top Keywords:
['about' 'as' 'be' 'but' 'can' 'from' 'has' 'have' 'how' 'it']

Sample POS Tags:
[('143', 'CD'), ('Miles', 'NNS'), ('in', 'IN'), ('35', 'CD'), ('Days', 'NNS'), (':', ':'), ('Lessons', 'NNS'), ('Learned', 'VBD'), ('Resting', 'NNP'), ('is', 'VBZ')]

Word2Vec Similar Words:
[('mental', 0.8333250284194946), ('care', 0.7965632081031799), ('act', 0.7956607341766357), ('affordable', 0.7736256122589111), ('insurance', 0.7656875848770142)]

Parsing Status: Completed
HMM Status: Completed
Neural Language Model: Created Successfully

In [49]:
df.to_csv("../outputs/preprocessed_news.csv", index=False)

In [50]:
from sklearn.metrics import classification_report

report = classification_report(y_test, predictions)

with open("../outputs/classification_report.txt", "w") as f:
    f.write(report)

print(report)

                precision    recall  f1-score   support

      BUSINESS       0.73      0.79      0.76       955
 ENTERTAINMENT       0.77      0.78      0.78       985
  FOOD & DRINK       0.86      0.83      0.84      1021
     PARENTING       0.79      0.77      0.78      1030
      POLITICS       0.80      0.75      0.78      1034
        SPORTS       0.85      0.88      0.86       995
STYLE & BEAUTY       0.87      0.83      0.85       986
        TRAVEL       0.81      0.80      0.81      1008
      WELLNESS       0.73      0.75      0.74      1009
    WORLD NEWS       0.79      0.82      0.80       977

      accuracy                           0.80     10000
     macro avg       0.80      0.80      0.80     10000
  weighted avg       0.80      0.80      0.80     10000

In [51]:
with open("../outputs/keywords.txt", "w") as f:
    for k in keywords:
        f.write(k + "\n")

In [52]:
with open("../outputs/final_results.txt", "w") as f:
    f.write(f"Accuracy: {accuracy}\n")
    f.write("\nKeywords:\n")
    f.write(str(keywords))